name: CI PIPELINE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_app.py
  
  build-docker:
    name: Build And Test Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image 
        run: docker build -t flask-api:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name api-container flask-api:${{ github.sha }}
          sleep 5

      - name: Test health endpoint
        run: curl -f http://localhost:5000/api/health
        
      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop api-container 
          docker rm api-container

  report: 
    name: Code Coverage Report
    needs: build-docker
    runs-on: ubuntu-latest

    steps:
      - name: Print pipeline summary
        run: |
          echo "Pipeline complete for commit: ${{ github.sha }}"

      - name: Test secretly
        env:
          MY_SECRET: ${{ secrets.LAB_SECRET }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Secret loaded successfully"
          else
            echo "Secret is missing!"
            exit 1
          fi
